version: '3.8'

services:
  # PostgreSQL cho Product Service
  product-db:
    image: postgres:15
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"  # PostgreSQL container sẽ nghe ở cổng 5432
    volumes:
      - product_db_data:/var/lib/postgresql/data
    networks:
      - fastfood

  product:
    build: ./services/product
    container_name: product-service
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - DB_HOST=product-db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=product_db
      - DB_PORT=5432
    depends_on:
      - product-db
    networks:
      - fastfood
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres", "-d", "product_db"]
        interval: 10s 
        retries: 5
        start_period: 15s
        timeout: 5s

  # PostgreSQL cho Order Service
  order-db:
    image: postgres:15
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5438:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    networks:
      - fastfood

  order:
    build: ./services/order
    container_name: order-service
    ports:
      - "3003:3000"
    environment:
      - PORT=3000
      - DB_HOST=order-db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=order_db
      - DB_PORT=5432
      - PRODUCT_URL=http://product:3000
    depends_on:
      - order-db
      - product
    networks:
      - fastfood
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "order_db"]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 5s 

  # PostgreSQL cho Payment Service
  payment-db:
    image: postgres:15
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5439:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    networks:
      - fastfood

  payment:
    build: ./services/payment
    container_name: payment-service
    ports:
      - "3004:3000"
    environment:
      - PORT=3000
      - DB_HOST=payment-db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=payment_db
      - DB_PORT=5432
      - ORDER_URL=http://order:3000
    depends_on:
      - payment-db
      - order
    networks:
      - fastfood
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "payment_db"]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 5s
    
  # PostgreSQL cho User Service
  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: 
      - "5433:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - fastfood
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "user_db"]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 5s

  # User Service
  user:
    build: ./services/user
    container_name: user-service
    ports: 
      - "3001:3000"
    environment:
      - PORT=3000
      - DB_HOST=user-db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=user_db
      - DB_PORT=5432
    depends_on:
      - user-db
    networks:
      - fastfood

  # Prometheus (Giám sát)
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - product
      - order
      - payment
    networks:
      - fastfood

  # Grafana (Hiển thị dữ liệu giám sát)
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3005:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - fastfood

  # pgAdmin (Công cụ quản lý PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - product-db
      - order-db
      - payment-db
    networks:
      - fastfood

networks:
  fastfood:
    driver: bridge

volumes:
  product_db_data:
  order_db_data:
  payment_db_data:
  user_db_data:
  pgadmin_data: