version: '3.8'

services:
  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

  user:
    build: ./services/user
    container_name: user-service
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - DB_HOST=user-db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=users_db
      - DB_PORT=5432
      - JWT_SECRET=supersecret
    depends_on:
      - user-db


  product-db:
    image: postgres:15
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data

  product:
    build: ./services/product
    container_name: product-service
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - DB_HOST=product-db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=product_db
      - DB_PORT=5432
    depends_on:
      - product-db


  order:
    build: ./services/order
    container_name: order-service
    ports:
      - "3003:3000"
    environment:
      - PORT=3000

  payment:
    build: ./services/payment
    container_name: payment-service
    ports:
      - "3004:3000"
    environment:
      - PORT=3000

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring:/etc/prometheus
    depends_on:
      - user
      - product
      - order
      - payment

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3005:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    depends_on:
      - prometheus
      
volumes:
  user_db_data:
  product_db_data: