version: '3.8'

services:
  # ===== API GATEWAY =====
  api-gateway:
    build: ./services/api-gateway
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT:-8080}:8080"
    environment:
      - PORT=8080
      - NODE_ENV=${NODE_ENV:-development}
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000}
      - USER_SERVICE_URL=http://user:3000
      - PRODUCT_SERVICE_URL=http://product:3000
      - ORDER_SERVICE_URL=http://order:3000
      - PAYMENT_SERVICE_URL=http://payment:3000
    depends_on:
      user:
        condition: service_healthy
      product:
        condition: service_healthy
      order:
        condition: service_healthy
      payment:
        condition: service_healthy
    networks:
      - fastfood
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ===== USER SERVICE =====
  user-db:
    image: postgres:15-alpine
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports: 
      - "5433:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - fastfood
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_db"]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 5s

  user:
    build: ./services/user
    container_name: user-service
    ports:
      - "${USER_SERVICE_PORT:-3001}:3000"
    environment:
      - PORT=3000
      - DB_HOST=user-db
      - DB_USER=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD:-password}
      - DB_NAME=user_db
      - DB_PORT=5432
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - fastfood
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ===== PRODUCT SERVICE =====
  product-db:
    image: postgres:15-alpine
    container_name: product-db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5434:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data
    networks:
      - fastfood
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d product_db"]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 5s

  product:
    build: ./services/product
    container_name: product-service
    ports:
      - "${PRODUCT_SERVICE_PORT:-3002}:3000"
    environment:
      - PORT=3000
      - DB_HOST=product-db
      - DB_USER=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD:-password}
      - DB_NAME=product_db
      - DB_PORT=5432
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      product-db:
        condition: service_healthy
    networks:
      - fastfood
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ===== ORDER SERVICE =====
  order-db:
    image: postgres:15-alpine
    container_name: order-db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5438:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    networks:
      - fastfood
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d order_db"]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 5s

  order:
    build: ./services/order
    container_name: order-service
    ports:
      - "${ORDER_SERVICE_PORT:-3003}:3000"
    environment:
      - PORT=3000
      - DB_HOST=order-db
      - DB_USER=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD:-password}
      - DB_NAME=order_db
      - DB_PORT=5432
      - PRODUCT_URL=http://product:3000
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      order-db:
        condition: service_healthy
      product:
        condition: service_healthy
    networks:
      - fastfood
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ===== PAYMENT SERVICE =====
  payment-db:
    image: postgres:15-alpine
    container_name: payment-db
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5439:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    networks:
      - fastfood
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payment_db"]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 5s

  payment:
    build: ./services/payment
    container_name: payment-service
    ports:
      - "${PAYMENT_SERVICE_PORT:-3004}:3000"
    environment:
      - PORT=3000
      - DB_HOST=payment-db
      - DB_USER=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD:-password}
      - DB_NAME=payment_db
      - DB_PORT=5432
      - ORDER_URL=http://order:3000
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      payment-db:
        condition: service_healthy
      order:
        condition: service_healthy
    networks:
      - fastfood
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ===== PROMETHEUS (MONITORING) =====
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - api-gateway
      - user
      - product
      - order
      - payment
    networks:
      - fastfood
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===== ALERTMANAGER =====
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    networks:
      - fastfood
    restart: unless-stopped

  # ===== GRAFANA (VISUALIZATION) =====
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GRAFANA_PORT:-3005}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - fastfood
    restart: unless-stopped

  # ===== PGADMIN (DATABASE MANAGEMENT) =====
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - user-db
      - product-db
      - order-db
      - payment-db
    networks:
      - fastfood
    restart: unless-stopped

networks:
  fastfood:
    driver: bridge
    name: fastfood-network

volumes:
  user_db_data:
    name: fastfood_user_db
  product_db_data:
    name: fastfood_product_db
  order_db_data:
    name: fastfood_order_db
  payment_db_data:
    name: fastfood_payment_db
  prometheus_data:
    name: fastfood_prometheus
  alertmanager_data:
    name: fastfood_alertmanager
  grafana_data:
    name: fastfood_grafana
  pgadmin_data:
    name: fastfood_pgadmin