name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.2
        options: --privileged
        ports:
          - 3000:3000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd services/user && npm install
          cd ../product && npm install
          cd ../order && npm install
          cd ../payment && npm install

      - name: Build Docker images
        run: |
          docker build -t fastfood-user ./services/user
          docker build -t fastfood-product ./services/product
          docker build -t fastfood-order ./services/order
          docker build -t fastfood-payment ./services/payment

      - name: Run containers temporarily
        run: |
          docker run -d -p 3001:3000 --name user-service fastfood-user
          docker run -d -p 3002:3000 --name product-service fastfood-product
          docker run -d -p 3003:3000 --name order-service fastfood-order
          docker run -d -p 3004:3000 --name payment-service fastfood-payment

      - name: Test dummy endpoints
        run: |
          curl -s http://localhost:3001/health
          curl -s http://localhost:3002/health
          curl -s http://localhost:3003/health
          curl -s http://localhost:3004/health

      - name: Stop and remove containers
        run: |
          docker rm -f user-service product-service order-service payment-service
